### ISSUE TITLE
Unexpected token 'e', "error code: 1003" is not valid JSON

### ISSUE THREAD

**Issue by TreeOfLearning** [triggerdotdev/examples#6]
Followed the cloudflare instructions exactly. The job executes perfectly against my local dev environment but when attempting to run on prod (cloudflare worker) I get the following error:

```
SyntaxError: Unexpected token 'e', "error code: 1003" is not valid JSON
    at async zodfetchWithVersions (index.js:13126:18)
    at async _ApiClient2.runTask (index.js:12698:12)
    at async _IO2.runTask (index.js:12246:22)
    at async _IOLogger2.callback (index.js:11460:9)
    at async Object.run (index.js:17319:7)
    at async #executeJob (index.js:14642:20)
    at async _TriggerClient2.handleRequest (index.js:14036:25)
    at async Array.<anonymous> (index.js:1106:22)
    at async index.js:16666:21
```

Note: I am running self hosted.

**Comment by TreeOfLearning** [comment]
Found the issue: my self hosted trigger instance url was just the IP address, and cloudflare workers don't support fetching from IP addresses. I put a reverse proxy in front of the instance and now all is good. 

I do think that it's worth looking into better reporting of errors like this, though. The initial error was quite cryptic. I don't think zodfetchWithVersions should blindly try to JSON.stringify the response - as seen here, the response is not guaranteed to be valid JSON!
